### ISSUE TITLE
allow declaring all the fields for OpenAPI spec parameter

### ISSUE THREAD

**Issue by ryskajakub** [Effect-TS/effect#4046]
### What is the problem this feature would solve?

When declaring api parameter, I can't declare some fields, that then would be displayed in rendered OpenApi

Those field are:
```
  readonly description?: string
  readonly deprecated?: boolean
  readonly allowEmptyValue?: boolean
```

### What is the feature you are proposing to solve the problem?

- take the description field from the schema description annotation
- check if `Schema.String` is min length 1, based on that set allowEmptyValue
- allow having `Schema.deprecated` method, that would have no effect on schema encoding/decoding, but just cause documentation rendering

### What alternatives have you considered?

use `Transform` annotation to top-level openapi object, walk deep into the structure and set the appropriate fields manually

**Comment by tim-smart** [comment]
You can use the `jsonSchema` annotation if you want to customize the output for a particular schema or property:

```ts
Schema.Struct({
  name: Schema.String.annotations({
    jsonSchema: {
      allowEmptyValue: true
    }
  })
})
```

**Comment by ryskajakub** [comment]
I did this on "@effect/platform": "^0.70.2":
```
      .setPath(
        Schema.Struct({
          month: YearMonth.annotations({ jsonSchema: { allowEmptyValue: true } }),
        }),
      )
```
and the result was:
```
      parameters:
        - name: month
          in: path
          schema:
            allowEmptyValue: true
          required: true
```
I expected this:
```
      parameters:
        - name: month
          in: path
          allowEmptyValue: true
          required: true

```
